### ISSUE TITLE
Investigate possible bug in CLI dataset generation

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk-data#27]
Filing because I've noticed it a few times: `openfisca-uk-data frs generate 2018` and `FRS.generate(2018)` producing different results (the Python interface producing correctly lower income tax and self-employed NI aggregates, and the CLI producing income tax of around £190bn, which is more accurate to the external figures, but it's not right because of the under-reporting of income in the FRS).

**Comment by MaxGhenis** [comment]
Is this still happening?

**Comment by nikhilwoodruff** [comment]
I don't think so
