### ISSUE TITLE
Fix negatives in income variables

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk-data#71]
Just noticed that private transfer income and maintenance income have some negative values.

**Comment by MaxGhenis** [comment]
Could you say more? What do negatives indicate and how should they be fixed?

**Comment by nikhilwoodruff** [comment]
Looks like it's reading a -1 in one of the respective income fields of the FRS (there are 12 between these two variables)

**Comment by MaxGhenis** [comment]
Does the FRS documentation say what -1 indicates? Often it'll mean missing. If so it makes sense to set it to zero but maybe over time we treat them differently so it could be in comments in #72.
